CC = gcc
CFLAGS = -g -Wall
SENDER_OBJECTS = rdtSender.c
RECEIVER_OBJECTS = rdtReceiver.c
NETWORK_OBJECTS = network.c
SENDER_NAME = sender
RECEIVER_NAME = receiver
NETWORK_NAME = proxy
TODELETE = $(SENDER_NAME) $(RECEIVER_NAME) $(NETWORK_NAME) *.o
LIBS = -pthread

all: $(SENDER_NAME) $(RECEIVER_NAME) $(NETWORK_NAME)

$(SENDER_NAME): $(SENDER_OBJECTS)
	$(CC) $(CFLAGS) $(SENDER_OBJECTS) $(LIBS) -o $(SENDER_NAME)

$(RECEIVER_NAME): $(RECEIVER_OBJECTS)
	$(CC) $(CFLAGS) $(RECEIVER_OBJECTS) $(LIBS) -o $(RECEIVER_NAME)

$(NETWORK_NAME): $(NETWORK_OBJECTS)
	$(CC) $(CFLAGS) $(NETWORK_OBJECTS) $(LIBS) -o $(NETWORK_NAME)

.PHONY: clean
clean:
	rm -f $(TODELETE)